load("//oci:defs.bzl", "oci_image", "oci_pull")
load("//tar:defs.bzl", "tar_file")

export_file(
    name = "test_sh",
    src = "test.sh",
    out = "test.sh",
)

tar_file(
    name = "app",
    srcs = [":test_sh"],
    out = "test.tar",
)

oci_pull(
    name = "alpine",
    image = "docker.io/library/alpine:3.20.0",
    digest = "sha256:216266c86fc4dcef5619930bd394245824c2af52fd21ba7c6fa0e618657d4c3b",
    platforms = ["linux/amd64"],
)

oci_image(
    name = "image",
    base = ":alpine",
    tars = [":app"],
    env = {
      "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    },
    entrypoint=["./test.sh"],
)
